//
//  PolymorphicMatchingTypesProviding.swift
//  KarrotCodableKit
//
//  Created by Elon on 8/4/26.
//  Copyright © 2026 Danggeun Market Inc. All rights reserved.
//

import Foundation

/// A ``PolymorphicCodableStrategy`` whose polymorphic family can be enumerated from the outside.
///
/// A plain ``PolymorphicCodableStrategy`` keeps its candidate types inside `decode(from:)`, so there is
/// no way to ask which types belong to the family. Conforming types expose that list as a value, which
/// lets callers cross-check the family against something else — for example, asserting in a test that
/// every declared type has a registered handler.
///
/// Strategies generated by `@PolymorphicCodableStrategyProviding` adopt this protocol automatically,
/// and their `decode(from:)` reads ``matchingTypes`` and ``fallbackType`` rather than repeating the
/// list, so the exposed family and the decoded family cannot drift apart. Hand-written strategies
/// adopt it only when they need to be enumerated.
///
/// ```swift
/// func assertEveryTypeHasHandler<Strategy: PolymorphicMatchingTypesProviding>(
///   declaredIn _: Strategy.Type,
///   registeredIdentifiers: Set<String>,
/// ) {
///   let declared = Set(Strategy.matchingTypes.map { $0.polymorphicIdentifier })
///   #expect(declared.subtracting(registeredIdentifiers).isEmpty)
/// }
///
/// assertEveryTypeHasHandler(
///   declaredIn: ViewItemCodableStrategy.self,
///   registeredIdentifiers: Set(handlers.keys),
/// )
/// ```
///
/// - Note: This protocol intentionally refines ``PolymorphicCodableStrategy`` instead of adding
///   requirements to it. A defaulted requirement on the base protocol would let a hand-written strategy
///   report an empty family, and an exhaustiveness check reading that value would pass vacuously.
public protocol PolymorphicMatchingTypesProviding: PolymorphicCodableStrategy {
  /// The candidate types matched against the polymorphic identifier, in the order they are matched.
  ///
  /// This is the same list `decode(from:)` uses.
  static var matchingTypes: [PolymorphicDecodableType.Type] { get }

  /// The type used when the identifier matches none of the ``matchingTypes``.
  ///
  /// `nil` means decoding fails with `PolymorphicCodableError.unableToFindPolymorphicType(_:)`
  /// instead of falling back.
  static var fallbackType: PolymorphicDecodableType.Type? { get }
}
